// <auto-generated />
namespace FormDesigner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class T1611061119 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(T1611061119));
        
        string IMigrationMetadata.Id
        {
            get { return "201611060331080_T1611061119"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
