// <auto-generated />
namespace FormDesigner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class T1611021059 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(T1611021059));
        
        string IMigrationMetadata.Id
        {
            get { return "201611020259339_T1611021059"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
